# Generated by Django 6.0 on 2025-12-03 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Data do Corte"
                    ),
                ),
                (
                    "horario",
                    models.TimeField(blank=True, null=True, verbose_name="Horário"),
                ),
                ("cliente", models.CharField(max_length=100)),
                (
                    "barbeiro",
                    models.CharField(
                        choices=[
                            ("LUCAS", "Lucas Borges"),
                            ("ALUIZIO", "Aluízio"),
                            ("ERIK", "Erik"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("DEGRADE", "Degradê"),
                            ("PEZIM", "Pezim"),
                            ("BARBA", "Barba"),
                            ("SOCIAL", "Social"),
                            ("COMPLETO", "Combo Completo"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "com_barba",
                    models.BooleanField(
                        default=False, verbose_name="Inclui Barba (+R$)?"
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "Pix"),
                            ("CARTAO", "Cartão"),
                            ("MISTO", "Misto (Dinheiro/Pix/Cartão)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor Total (R$)"
                    ),
                ),
                (
                    "valor_1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Parte 1 (Misto)",
                    ),
                ),
                (
                    "valor_2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Parte 2 (Misto)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Saida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=datetime.date.today)),
                (
                    "descricao",
                    models.CharField(
                        max_length=200, verbose_name="Descrição da Despesa"
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("categoria", models.CharField(default="Geral", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=datetime.date.today)),
                (
                    "item",
                    models.CharField(max_length=200, verbose_name="Produto Vendido"),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "vendedor",
                    models.CharField(
                        choices=[
                            ("LUCAS", "Lucas Borges"),
                            ("ALUIZIO", "Aluízio"),
                            ("ERIK", "Erik"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
