# Generated by Django 6.0 on 2025-12-04 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saida",
            name="categoria",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="tipo_pagamento_1",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="tipo_pagamento_2",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="com_barba",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="data",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("CARTAO", "Cartão"),
                    ("MISTO", "Misto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="servico",
            field=models.CharField(
                choices=[
                    ("DEGRADE", "Degradê"),
                    ("SOCIAL", "Social"),
                    ("PEZIM", "Pezim"),
                    ("BARBA", "Barba"),
                    ("SOBRANCELHA", "Sobrancelha"),
                    ("LUZES", "Luzes"),
                    ("PLATINADO", "Platinado"),
                    ("ALISAMENTO", "Alisamento"),
                    ("PIGMENTACAO", "Pigmentação"),
                    ("COMPLETO", "Combo Completo"),
                    ("OUTRO", "Outro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="valor_1",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="valor_2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="saida",
            name="descricao",
            field=models.CharField(max_length=200, verbose_name="Descrição da Saída"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="item",
            field=models.CharField(max_length=200, verbose_name="Descrição do Produto"),
        ),
        migrations.AlterField(
            model_name="venda",
            name="vendedor",
            field=models.CharField(
                choices=[
                    ("LUCAS", "Lucas Borges"),
                    ("ALUIZIO", "Aluízio"),
                    ("ERIK", "Erik"),
                    ("FABRICIO", "Fabrício"),
                ],
                max_length=50,
            ),
        ),
    ]
