# Generated by Django 6.0 on 2025-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_saida_categoria_agendamento_tipo_pagamento_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendamento",
            name="servico",
            field=models.CharField(
                choices=[
                    ("TRADICIONAL", "Tradicional"),
                    ("PEZIM", "Pezim"),
                    ("DEGRADE", "Degradê"),
                    ("NAVALHADO", "Navalhado"),
                    ("SOCIAL", "Social"),
                    ("BARBA", "Barba"),
                    ("CONSULTORIA", "Consultoria de Visagismo"),
                    ("ABORDAGEM", "Abordagem de Visagismo"),
                ],
                max_length=20,
            ),
        ),
    ]
